asp_presentacion/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace asp_presentacion.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

asp_presentacion/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace asp_presentacion.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

asp_presentacion/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace asp_presentacion.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }

}

asp_presentacion/Pages/Ventanas/Personas.cshtml.cs
using lib_entidades.Modelos;
using lib_presentaciones.Interfaces;
using lib_utilidades;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace asp_presentacion.Pages.Ventanas
{
    public class PersonasModel : PageModel
    {
        private IPersonasPresentacion? iPresentacion = null;

        public PersonasModel(IPersonasPresentacion iPresentacion)
        {
            try
            {
                this.iPresentacion = iPresentacion;
                Filtro = new Personas();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        [BindProperty] public Enumerables.Ventanas Accion { get; set; }
        [BindProperty] public Personas? Actual { get; set; }
        [BindProperty] public Personas? Filtro { get; set; }
        [BindProperty] public List<Personas>? Lista { get; set; }

        public virtual void OnGet() { OnPostBtRefrescar(); }

        public void OnPostBtRefrescar()
        {
            try
            {
                Filtro!.Cedula = Filtro!.Cedula ?? "";
                Filtro!.Nombre = "Mateo";

                Accion = Enumerables.Ventanas.Listas;
                var task = this.iPresentacion!.Buscar(Filtro!, "NOMBRE");
                task.Wait();
                Lista = task.Result;
                Actual = null;
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtNuevo()
        {
            try
            {
                Accion = Enumerables.Ventanas.Editar;
                Actual = new Personas()
                {
                    Edad = 20,
                };
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtModificar(string data)
        {
            try
            {
                OnPostBtRefrescar();
                Accion = Enumerables.Ventanas.Editar;
                Actual = Lista!.FirstOrDefault(x => x.Id.ToString() == data);
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtGuardar()
        {
            try
            {
                Accion = Enumerables.Ventanas.Editar;
                Task<Personas>? task = null;
                if (Actual!.Id == 0)
                    task = this.iPresentacion!.Guardar(Actual!);
                else
                    task = this.iPresentacion!.Modificar(Actual!);
                task.Wait();
                Actual = task.Result;
                Accion = Enumerables.Ventanas.Listas;
                OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtBorrarVal(string data)
        {
            try
            {
                OnPostBtRefrescar();
                Accion = Enumerables.Ventanas.Borrar;
                Actual = Lista!.FirstOrDefault(x => x.Id.ToString() == data);
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtBorrar()
        {
            try
            {
                var task = this.iPresentacion!.Borrar(Actual!);
                Actual = task.Result;
                OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public void OnPostBtCancelar()
        {
            try
            {
                Accion = Enumerables.Ventanas.Listas;
                OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public void OnPostBtCerrar()
        {
            try
            {
                if (Accion == Enumerables.Ventanas.Listas)
                    OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }
    }
}

asp_presentacion/Pages/Emergentes/Mensajes.cshtml
<center>
    <div class='popup'>
        <div class='pp_ms_inner'>
            <div style='width:95%'>
                <h2 align="left">
                    @lib_lenguajes.RsMenu.lbMensaje
                </h2>
                <h4 align="left">
                    @ViewData["Mensaje"]
                </h4>
                <input type="submit"
                       value="@lib_lenguajes.RsMenu.lbCerrar"
                       asp-page-handler="BtCerrar"
                       class="btn btn-secondary" />
            </div>
        </div>
    </div>
</center>

asp_presentacion/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Mapa General";
}
@* implementamos Leaflet.js para el uso del mapa *@
<link rel="stylesheet" href="https://unpkg.com/leaflet/dist/leaflet.css" />
<script src="https://unpkg.com/leaflet/dist/leaflet.js"></script>

@* inicializamos un tamaño para el mapa *@
<div id="map" style="height: 400px; width: 100%;"></div>

@* realizamos el punto por defecto del mapa y se establece la conecion con OpenStreetMap *@
<script>
    const map = L.map('map').setView([6.25184, -75.56359], 13);

    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        maxZoom: 19,
        attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
    }).addTo(map);

    L.marker([6.25184, -75.56359]).addTo(map)
        .bindPopup('Marca por defecto')
        .openPopup();
</script>

asp_presentacion/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - asp_presentacion</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/asp_presentacion.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">asp_presentacion</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark"
                               asp-area=""
                               asp-page="/Index">
                                Mapa general
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark"
                               asp-area=""
                               asp-page="/Privacy">
                                Privacy
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark"
                               asp-area=""
                               asp-page="/Ventanas/Personas">
                                Personas
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - asp_presentacion - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

asp_presentacion/Pages/Ventanas/Personas.cshtml
@page
@model asp_presentacion.Pages.Ventanas.PersonasModel
@{
    ViewData["Titulo"] = lib_lenguajes.RsMenu.lbPersonas;
}
<center>
    <div>
        <form method="POST"
              enctype="multipart/form-data">
            @Html.AntiForgeryToken()

            <div align="left">
                <h3>@lib_lenguajes.RsMenu.lbPersonas</h3>
            </div>
            <div align="left"
                 class="bt_panel_buttons">
                <input type="submit"
                       value="@lib_lenguajes.RsMenu.lbRefrescar"
                       asp-page-handler="BtRefrescar"
                       class="btn btn-secondary"
                       disabled="@(Model.Accion != lib_utilidades.Enumerables.Ventanas.Listas)" />
                <input type="submit"
                       value="@lib_lenguajes.RsMenu.lbNuevo"
                       asp-page-handler="BtNuevo"
                       class="btn btn-secondary"
                       disabled="@(Model.Accion != lib_utilidades.Enumerables.Ventanas.Listas)" />
                <input type="submit"
                       value="@lib_lenguajes.RsMenu.lbGuardar"
                       asp-page-handler="BtGuardar"
                       class="btn btn-secondary"
                       disabled="@(Model.Accion == lib_utilidades.Enumerables.Ventanas.Listas)" />
                <input type="submit"
                       value="@lib_lenguajes.RsMenu.lbCancelar"
                       asp-page-handler="BtCancelar"
                       class="btn btn-secondary"
                       disabled="@(Model.Accion == lib_utilidades.Enumerables.Ventanas.Listas)" />
            </div>

            @if (Model.Accion != lib_utilidades.Enumerables.Ventanas.Listas ||
            Model.Accion == lib_utilidades.Enumerables.Ventanas.Borrar)
            {
                <input type="hidden"
                       asp-for="@Model.Actual!.Id" />
                <input type="hidden"
                       asp-for="@Model.Actual!.Nombre" />
            }
            @if (Model.Accion == lib_utilidades.Enumerables.Ventanas.Borrar)
            {
                <input type="hidden"
                       asp-for="@Model.Actual!.Id" />
                <input type="hidden"
                       asp-for="@Model.Actual!.Cedula" />
                <input type="hidden"
                       asp-for="@Model.Actual!.Nombre" />
                <input type="hidden"
                       asp-for="@Model.Actual!.Edad" />
                <input type="hidden"
                       asp-for="@Model.Actual!.Activo" />
            }

            @if (Model.Accion == lib_utilidades.Enumerables.Ventanas.Editar)
            {
                <div class="containers_vn panel panel-default">
                    <h3>Localizaciones</h3>

                    <div>
                        <div class="form-group">
                            <label class="col-lg-4 control-label">
                                Nombre
                            </label>
                            <div class="col-lg-6">
                                <input id="nmPersona"
                                       class="cts_forms form-control"
                                       asp-for="@Model.Actual!.Nombre" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-lg-4 control-label">
                                Cedula
                            </label>
                            <div class="col-lg-6">
                                <input id="nmCedula"
                                       class="cts_forms form-control"
                                       asp-for="@Model.Actual!.Cedula" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-lg-4 control-label">
                                Edad
                            </label>
                            <div class="col-lg-6">
                                <input id="nmEdad"
                                       class="cts_forms form-control"
                                       asp-for="@Model.Actual!.Edad" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-lg-4 control-label">
                                Activo
                            </label>
                            <div class="col-lg-6">
                                <input id="nmActivo"
                                       class="cts_forms form-control"
                                       asp-for="@Model.Actual!.Activo" />
                            </div>
                        </div>
                    </div>
               </div>
            }

            @if (ViewData.ContainsKey("Mensaje"))
            {
                <input type="hidden"
                       asp-for="@Model.Accion" />
                @await Html.PartialAsync(
                         "../Emergentes/Mensajes.cshtml")
            }

            @if (Model.Accion == lib_utilidades.Enumerables.Ventanas.Borrar)
            {
                <div class='popup'>
                    <div class='pp_del_inner'>
                        <div style='width:95%'>
                            <h2 align="left">
                                @lib_lenguajes.RsMenu.lbMensaje
                            </h2>

                            <h4 align="left">
                                @lib_lenguajes.RsMenu.lbBorrarEntidad
                            </h4>
                            <h6 align="left">
                                @Model.Actual!.Id
                            </h6>
                            <br />
                            <br />
                            <input type="submit"
                                   value="@lib_lenguajes.RsMenu.lbBorrar"
                                   asp-page-handler="BtBorrar"
                                   class="btn btn-secondary" />
                            <input type="submit"
                                   value="@lib_lenguajes.RsMenu.lbCerrar"
                                   asp-page-handler="BtCancelar"
                                   class="btn btn-secondary" />
                        </div>
                    </div>
                </div>
            }

            @if (Model.Accion == lib_utilidades.Enumerables.Ventanas.Listas ||
            Model.Accion == lib_utilidades.Enumerables.Ventanas.Borrar)
            {
                <input id="flNombre"
                       class="cts_forms form-control"
                       asp-for="@Model.Filtro!.Edad"
                       placeholder="@lib_lenguajes.RsPersonas.lbEdad" />
                <br />

                <div class="containers_vn panel panel-default">
                    <table class="tb_data table table-striped table-bordered table-hover">
                        <tr>
                            <th>
                                Id
                            </th>
                            <th class="cl_hidden">
                                Cedula
                            </th>
                            <th class="cl_hidden">
                                Nombre
                            </th>
                            <th class="cl_hidden">
                                Edad
                            </th>
                            <th class="cl_hidden">
                                Activo
                            </th>
                            <th class="cl_actions">
                                Accion
                            </th>
                        </tr>
                        @if (Model != null && Model.Lista != null)
                        {
                            @foreach (var elemento in Model.Lista)
                            {
                                <tr>
                                    <td>
                                        @elemento.Id
                                    </td>
                                    <td class="cl_hidden">
                                        @elemento.Cedula
                                    </td>
                                    <td class="cl_hidden">
                                        @elemento.Nombre
                                    </td>
                                    <td class="cl_hidden">
                                        @elemento.Edad
                                    </td>
                                    <td class="cl_hidden">
                                        @elemento.Activo
                                    </td>
                                    <td>
                                        <input type="submit"
                                               value="@lib_lenguajes.RsMenu.lbModicar"
                                               asp-page-handler="BtModificar"
                                               class="btn btn-secondary"
                                               asp-route-data="@elemento.Id" />
                                        <input type="submit"
                                               value="@lib_lenguajes.RsMenu.lbBorrar"
                                               asp-page-handler="BtBorrarVal"
                                               class="btn btn-secondary"
                                               asp-route-data="@elemento.Id" />
                                    </td>
                                </tr>
                            }
                        }
                    </table>
                </div>
            }
        </form>
    </div>
</center>